FROM python:3.12-slim-bookworm
LABEL maintainer="sinfallas@gmail.com"
LABEL build_date="2025-01-10"
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app
RUN apt update -qq && apt -y dist-upgrade && apt -y install --no-install-recommends --no-install-suggests curl git && apt clean && apt -y autoremove && rm -rf /var/lib/{apt,dpkg,cache,log} && rm -rf /var/cache/* && rm -rf /var/log/apt/* && rm -rf /tmp/*
RUN git clone https://github.com/comfyanonymous/ComfyUI.git .
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/xpu
RUN pip install -r requirements.txt
RUN pip install -r manager_requirements.txt
EXPOSE 8188
CMD ["python","main.py","--listen","0.0.0.0","--front-end-version","Comfy-Org/ComfyUI_frontend@latest"]
